-- MySQL Script generated by MySQL Workbench
-- 02/12/16 23:22:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dictionary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dictionary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `<?php echo base_url(); ?>images/` DEFAULT CHARACTER SET utf8 ;
USE `dictionary` ;

-- -----------------------------------------------------
-- Table `dictionary`.`tbl_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dictionary`.`tbl_users` (
  `users_id` INT NOT NULL AUTO_INCREMENT,
  `users_full_name` VARCHAR(200) NULL,
  `gender` INT NULL,
  `users_name` VARCHAR(45) NULL,
  `users_password` VARCHAR(200) NULL,
  `deleted` INT NULL,
  `users_date` TIMESTAMP NULL,
  PRIMARY KEY (`users_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dictionary`.`tbl_keywords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dictionary`.`tbl_keywords` (
  `keywords_id` INT NOT NULL AUTO_INCREMENT,
  `keywords_date` TIMESTAMP NULL,
  `keywords_title` VARCHAR(200) NULL,
  `deleted` INT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`keywords_id`),
  INDEX `fk_tbl_keywords_tbl_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_tbl_keywords_tbl_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `dictionary`.`tbl_users` (`users_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dictionary`.`tbl_explains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dictionary`.`tbl_explains` (
  `explains_id` INT NOT NULL AUTO_INCREMENT,
  `explains_english` TEXT NULL,
  `explains_khmer` TEXT NULL,
  `deleted` INT NULL,
  `keywords_id` INT NOT NULL,
  PRIMARY KEY (`explains_id`, `keywords_id`),
  INDEX `fk_tbl_explains_tbl_keywords_idx` (`keywords_id` ASC),
  CONSTRAINT `fk_tbl_explains_tbl_keywords`
    FOREIGN KEY (`keywords_id`)
    REFERENCES `dictionary`.`tbl_keywords` (`keywords_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
